apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ec2-demo-runner
  title: demo-runner (EC2 instance)
  description: "Demo utility server"
  tags:
    - aws
    - ec2
  links:
    - url: https://ap-south-1.console.aws.amazon.com/ec2/home?region=ap-south-1#Instances:tag:Name=devops94-idp-res-demo-runner
      title: EC2 console
      icon: cloud
    - url: https://github.com/0019-KDU/platform-resources/tree/main/resources/ec2-instance/demo-runner
      title: Terraform definition
      icon: github
spec:
  type: virtual-machine
  owner: group:default/platform-admins
  system: idp-demo
