apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: s3-dev-shop-images
  title: shop-images [dev] (S3 bucket)
  description: "Product images for shop-api"
  annotations:
    aws.amazon.com/cost-insights-tags: resource=shop-images,resource-type=s3-bucket,environment=dev
  tags:
    - aws
    - s3
  links:
    - url: https://s3.console.aws.amazon.com/s3/buckets/devops94-idp-dev-res-shop-images-697502032879?region=ap-south-1
      title: S3 console
      icon: cloud
    - url: https://github.com/0019-KDU/platform-resources/tree/main/resources/s3-bucket/dev/shop-images
      title: Terraform definition
      icon: github
spec:
  type: s3-bucket
  owner: group:default/platform-admins
  system: idp-demo
  dependencyOf:
    - component:default/shop-api
